language: java
before_install: echo $HOME

script:
  - echo "skipping tests"

before_deploy:
  - cd /node_modules/igpop/bin && https://ru.files.fm/down.php?i=y27hscjj -o igpop.jar
  - cd /node_modules/igpop/bin && java -jar igpop.jar build "/igpop-example"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
