language: java
before_install: echo $HOME

script:
  - echo "skipping tests"

before_deploy:
  - npm install
  - java -jar "../npm/igpop/bin/igpop.jar" build "/igpop" igpop.core

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
