language: java
before_install: echo $HOME

script:
  - echo "skipping tests"

before_deploy:
  - curl https://ru.files.fm/down.php?i=y27hscjj -o igpop.jar
  - java -jar igpop.jar build "/igpop-example"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
