language: clojure
before_install: echo $HOME
install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.469.sh
  - chmod +x linux-install-1.10.1.469.sh
  - sudo ./linux-install-1.10.1.469.sh
  - rm linux-install-1.10.1.469.sh

script:
  - echo "skipping tests"

before_deploy:
  - npm install
  - git submodule init
  - git submodule update --remote
  - (cd igpop && make build)
  - java -jar "./igpop/target/igpop.jar" build "/igpop-example"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master