description: 'Base StructureDefinition for Meta Type: The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.'
kind: complex-type
elements:
  id:
    description: Unique id for inter-element referencing
    type: string
  versionId:
    description: Version specific identifier
    type: id
  lastUpdated:
    description: When the resource version last changed
    type: instant
  source:
    description: Identifies where the resource comes from
    type: uri
  profile: #[]
    collection: true
    description: Profiles this resource claims to conform to
    type: canonical
  security: #[]
    collection: true
    description: Security Labels applied to this resource
    type: Coding
  tag: #[]
    collection: true
    description: Tags applied to this resource
    type: Coding