description: 'Base StructureDefinition for ProdCharacteristic Type: The marketing status describes the date when a medicinal product is actually put on the market or the date as of which it is no longer available.'
kind: complex-type
elements:
  id:
    description: Unique id for inter-element referencing
    type: string
  height:
    description: Where applicable, the height can be specified using a numerical value and its unit of measurement The unit of measurement shall be specified in accordance with ISO 11240 and the resulting terminology The symbol and the symbol identifier shall be used
    type: Quantity
  width:
    description: Where applicable, the width can be specified using a numerical value and its unit of measurement The unit of measurement shall be specified in accordance with ISO 11240 and the resulting terminology The symbol and the symbol identifier shall be used
    type: Quantity
  depth:
    description: Where applicable, the depth can be specified using a numerical value and its unit of measurement The unit of measurement shall be specified in accordance with ISO 11240 and the resulting terminology The symbol and the symbol identifier shall be used
    type: Quantity
  weight:
    description: Where applicable, the weight can be specified using a numerical value and its unit of measurement The unit of measurement shall be specified in accordance with ISO 11240 and the resulting terminology The symbol and the symbol identifier shall be used
    type: Quantity
  nominalVolume:
    description: Where applicable, the nominal volume can be specified using a numerical value and its unit of measurement The unit of measurement shall be specified in accordance with ISO 11240 and the resulting terminology The symbol and the symbol identifier shall be used
    type: Quantity
  externalDiameter:
    description: Where applicable, the external diameter can be specified using a numerical value and its unit of measurement The unit of measurement shall be specified in accordance with ISO 11240 and the resulting terminology The symbol and the symbol identifier shall be used
    type: Quantity
  shape:
    description: Where applicable, the shape can be specified An appropriate controlled vocabulary shall be used The term and the term identifier shall be used
    type: string
  color: #[]
    collection: true
    description: Where applicable, the color can be specified An appropriate controlled vocabulary shall be used The term and the term identifier shall be used
    type: string
  imprint: #[]
    collection: true
    description: Where applicable, the imprint can be specified as text
    type: string
  image: #[]
    collection: true
    description: Where applicable, the image can be provided The format of the image attachment shall be specified by regional implementations
    type: Attachment
  scoring:
    description: Where applicable, the scoring can be specified An appropriate controlled vocabulary shall be used The term and the term identifier shall be used
    type: CodeableConcept